# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_auto_20160108_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anketa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studystage',
            options={},
        ),
    ]
