# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_auto_20160108_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anketa',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='group',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='studyStage',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='Anketa',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='StudyStage',
        ),
    ]
